SelectFile_btn_selectfile="SelectFile_btn_selectfile"
tab_cnc_simulation_request_btn_home_cnc="tab_cnc_simulation_request_btn_home_cnc"
tab_cnc_simulation_request_btn_run_cnc="tab_cnc_simulation_request_btn_run_cnc"
tab_start_btn_print="tab_start_btn_print"
